# Generated by Django 2.0.5 on 2018-05-09 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeptEmp',
            fields=[
                ('deptemp_id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('dept_id', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.DO_NOTHING, to='users.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='DeptManager',
            fields=[
                ('deptmanager_id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('dept_id', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.DO_NOTHING, to='users.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(blank=True, max_length=14)),
                ('last_name', models.CharField(blank=True, max_length=16)),
                ('gender', models.TextField(blank=True)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('salary', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('title_id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.DO_NOTHING, to='users.Employees')),
            ],
        ),
        migrations.AddField(
            model_name='deptmanager',
            name='emp_id',
            field=models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.DO_NOTHING, to='users.Employees'),
        ),
        migrations.AddField(
            model_name='deptemp',
            name='emp_id',
            field=models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.DO_NOTHING, to='users.Employees'),
        ),
    ]
