# Generated by Django 2.0.5 on 2018-05-08 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dept'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dept',
            options={},
        ),
    ]
