# Generated by Django 2.0.5 on 2018-05-08 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180507_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='name',
        ),
    ]
