# Generated by Django 2.0.5 on 2018-05-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='emp_no',
            new_name='emp_id',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='id',
        ),
        migrations.AddField(
            model_name='salary',
            name='salary_id',
            field=models.IntegerField(default=False, primary_key=True, serialize=False),
        ),
    ]
